### ISSUE TITLE
Error while depolying

### ISSUE THREAD

**Issue by skilledDeveloper** [apancutt/aws-eb-newrelic-deploynotify#2]
I got error: "You don't have permission to execute ...."
and fixed it by adding the following command before the main command:

```
command: "chmod +x bin/aws-eb-newrelic-deploynotify.sh"
```

The configuration will look like this:

```
container_commands:
  "01":
    command: "chmod +x bin/aws-eb-newrelic-deploynotify.sh"
  "02":
    command: "bin/aws-eb-newrelic-deploynotify.sh -a <appName> -k <api-key>"
    leader_only: true
```

**Comment by apancutt** [comment]
Sounds like you're using a local filesystem that doesn't support the executable bit. Please confirm your environment and, if it's Windows, please try again using Cygwin.

**Comment by skilledDeveloper** [comment]
That's right. I was using Windows but it's safe to have `chmod +x`.
